name: CI/CD 

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-test-solution:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: build .NET
      run: make dotnet-build
    - name: test .NET
      run: make dotnet-test
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
    - name: ACR build
      id: acr
      uses: azure/acr-build@v1
      with:
        git_access_token:           ${{ secrets.git_access_token }}
        service_principal:          ${{ secrets.service_principal_id }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant:                     ${{ secrets.service_principal_tenant }}
        registry:                   ${{ secrets.registry }}
        repository:                 ${{ secrets.repository }}
        image:                      ${{ secrets.image }}
        folder:     ./
        dockerfile: ./Dockerfile
        branch:     main
    
  
