# WINDOWS
#
# We'll use some Unix commands here: install git bash with all Unix commands on the PATH
# We'll need `make`: run `choco install make`

-include .config/subscription.cfg
-include .config/organization.cfg
-include .config/project.cfg

-include .makefiles/Common.Makefile
-include .makefiles/Setup.Organization.Makefile
-include .makefiles/Setup.Project.Makefile
-include .makefiles/Targets.Dotnet.Makefile
-include .makefiles/Targets.Docker.Makefile
-include .makefiles/Targets.K8s.Makefile
-include .makefiles/Targets.Az.Makefile
-include .makefiles/Targets.AKS.Makefile